# Generated by Django 3.0.2 on 2020-02-03 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('license_plate_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('special_vehicle_info', models.TextField(blank=True, max_length=200, null=True, verbose_name='special_vehicle_info')),
                ('vehicle_type', models.CharField(blank=True, choices=[('ux', 'uberx'), ('cf', 'comfort'), ('ul', 'uberxl')], default='cf', help_text='Vehicle type', max_length=2)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique Ride ID', primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('ux', 'uberx'), ('cf', 'comfort'), ('ul', 'uberxl')], help_text='optinal vehicle type request', max_length=2, null=True)),
                ('special_vehicle_info', models.TextField(blank=True, max_length=200, null=True, verbose_name='special_vehicle_info')),
                ('status', models.CharField(blank=True, choices=[('op', 'open'), ('cf', 'Confirmed'), ('cp', 'Complete')], default='op', help_text='ride status', max_length=2)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_ride', to='pancakeride.Driver')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_ride', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sharer_ride', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
