# Generated by Django 3.0.2 on 2020-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancakeride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='shareable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='sharer_num',
            field=models.IntegerField(default=0),
        ),
    ]
