# Generated by Django 3.0.2 on 2020-02-04 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pancakeride', '0002_auto_20200203_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passenger_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
